annotations:
  category: Infrastructure
  images: |
    - name: rabbitmq-cluster-operator
      image: docker.io/bitnami/rabbitmq-cluster-operator:2.6.0-debian-11-r1
    - name: rabbitmq
      image: docker.io/bitnami/rabbitmq:3.11.26-debian-11-r1
    - name: rmq-default-credential-updater
      image: docker.io/bitnami/rmq-default-credential-updater:1.0.4-debian-11-r3
    - name: rmq-messaging-topology-operator
      image: docker.io/bitnami/rmq-messaging-topology-operator:1.12.1-debian-11-r3
  licenses: Apache-2.0
apiVersion: v2
appVersion: 2.6.0
dependencies:
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: The RabbitMQ Cluster Kubernetes Operator automates provisioning, management,
  and operations of RabbitMQ clusters running on Kubernetes.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/rabbitmq-cluster-operator/img/rabbitmq-cluster-operator-stack-220x234.png
keywords:
- rabbitmq
- operator
- infrastructure
- message queue
- AMQP
kubeVersion: '>= 1.19.0-0'
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: rabbitmq-cluster-operator
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/rabbitmq-cluster-operator
version: 3.10.7
